### ISSUE TITLE
Swap out gulp &  browserify for webpack

### ISSUE THREAD

**Issue by jnmarcus** [caciviclab/disclosure-frontend#60] opened 2015-12-30 04:25 UTC

**Comment by tdooner** [comment] 2015-12-30 04:44
Can you explain what this will buy us?

**Comment by KyleW** [comment] 2016-07-19 16:08
I share Tom's reaction that switching out tooling is time consuming and doesn't move the ball forward in terms of features so we should put it off. However, I spent a bunch of time last night fighting with browserify plugins that don't quite work as intended. The seed project we started with used every plugin out there and it's now a real hassle to maintain.

I'll continue to configure plugins until this thing works smoothly and then document the most important gulp tasks.

**Comment by tdooner** [comment] 2016-07-20 03:56
Okay yeah, thanks for the bump. I have had pretty good experience with Webpack at work, so I think it is a promising solution if we continue to hit browserify snags.

But I am optimistic that kyle's JS configuration mojo will allow us to simplify our browserify pipeline enough so it is not flaky. And that will be more straightforward than swapping it out wholesale.

I'm closing this for now, so that newcomers to the project don't accidentally think this is a high-priority piece of work.

**Closed by tdooner** 2016-07-20 03:56 UTC
Labels: enhancement
